# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Hanifa Pilvar
description: >- # this means to ignore newlines until "baseurl:"
  This is my personal website.
baseurl: "/" # the subpath of the site
url: "https://hanifa-pilvar.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Research
    - name: Teaching

footer:
  show_powered_by: False
  contact:
    - name: Email
      value: h.pilvar[at]qmul.ac.uk
      link: mailto:h.pilvar@qmul.ac.uk
  follow:
    - name: Google Scholar
      link: https://scholar.google.dk/citations?hl=da&user=L9ALJ20AAAAJ
    - name: LinkedIn
      link: http://linkedin.com/in/YourLinkedInUsername

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
